### Python Pandas Tutorials- Part 1

In Part 1 we are going to learn about
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [ ]:
## for different code studios
!pip install pandas

In [5]:
import pandas as pd
import numpy as np

In [7]:
data1 = np.arange(1,21).reshape(4,5)

In [8]:
data1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
## Create DataFrame
pd.DataFrame(data=data1,index = ['Row1','Row2','Row3','Row4'], columns = ['Column1','Column2','Column3','Column4','Column5'])

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [14]:
Dataframe= pd.DataFrame(data=data1,index = ['Row1','Row2','Row3','Row4'], columns = ['Column1','Column2','Column3','Column4','Column5'])

In [15]:
type(Dataframe)

pandas.core.frame.DataFrame

In [18]:
Dataframe.head()    ## for top 5

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [17]:
Dataframe.tail()  ## for lower 5

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [19]:
Dataframe.info()   ## data info

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  4 non-null      int64
 1   Column2  4 non-null      int64
 2   Column3  4 non-null      int64
 3   Column4  4 non-null      int64
 4   Column5  4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


In [21]:
Dataframe.describe()   ## complete describe the data

Column1    Column2    Column3    Column4    Column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    8.500000   9.500000  10.500000  11.500000  12.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%     4.750000   5.750000   6.750000   7.750000   8.750000
50%     8.500000   9.500000  10.500000  11.500000  12.500000
75%    12.250000  13.250000  14.250000  15.250000  16.250000
max    16.000000  17.000000  18.000000  19.000000  20.000000

In [29]:
  ##Indexing
## columnname,rowindex[.loc],rowindex columnindex number[.iloc]
Dataframe.head()

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [24]:
## indexing by column name
Dataframe['Column4']

Row1     4
Row2     9
Row3    14
Row4    19
Name: Column4, dtype: int64

In [25]:
type(Dataframe['Column4'])

pandas.core.series.Series

In [26]:
Dataframe[['Column3','Column4']]

Column3  Column4
Row1        3        4
Row2        8        9
Row3       13       14
Row4       18       19

In [27]:
type(Dataframe[['Column3','Column4']])

pandas.core.frame.DataFrame

In [34]:
## indexing using row index name [.loc]
Dataframe.loc['Row3']

Column1    11
Column2    12
Column3    13
Column4    14
Column5    15
Name: Row3, dtype: int64

In [31]:
type(Dataframe.loc['Row3'])

pandas.core.series.Series

In [32]:
Dataframe.loc[['Row2','Row4','Row3']]

Column1  Column2  Column3  Column4  Column5
Row2        6        7        8        9       10
Row4       16       17       18       19       20
Row3       11       12       13       14       15

In [33]:
type(Dataframe.loc[['Row2','Row4','Row3']])

pandas.core.frame.DataFrame

In [35]:
## indexing using both rowindex columnindex number[.iloc]
Dataframe

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [39]:
Dataframe.iloc[2:,2:4]

Column3  Column4
Row3       13       14
Row4       18       19

In [40]:
Dataframe.iloc[:,::4]

Column1  Column5
Row1        1        5
Row2        6       10
Row3       11       15
Row4       16       20

In [41]:
Dataframe[['Column1','Column5']]

Column1  Column5
Row1        1        5
Row2        6       10
Row3       11       15
Row4       16       20

In [44]:
## to covert DaraFrame into arrays
Dataframe

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [43]:
Dataframe.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [45]:
## Basic operations
Dataframe.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
dtype: int64

In [48]:
Df = pd.DataFrame(data = [[1,np.nan,2],[5,6,7]],index = ['Row1','Row2'], columns = ['Column1','Column2','Column3'])

In [49]:
Df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        5      6.0        7

In [50]:
Df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [51]:
Df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [57]:
Df.isnull().sum==0

False

In [58]:
Df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [59]:
Df.isnull()==0

Column1  Column2  Column3
Row1     True    False     True
Row2     True     True     True

In [60]:
Df.isnull==0

False

In [61]:
Df.isnull().sum()!=0

Column1    False
Column2     True
Column3    False
dtype: bool

In [63]:
Dataframe

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

In [64]:
Dataframe['Column3'].value_counts()

Column3
3     1
8     1
13    1
18    1
Name: count, dtype: int64

In [65]:
Dataframe['Column5'].unique()

array([ 5, 10, 15, 20])

In [66]:
Dataframe['Column5']%2==0

Row1    False
Row2     True
Row3    False
Row4     True
Name: Column5, dtype: bool

In [67]:
Dataframe[Dataframe['Column5']%2==0]

Column1  Column2  Column3  Column4  Column5
Row2        6        7        8        9       10
Row4       16       17       18       19       20