## Python Numpy Arrays 

## Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## import the library
import numpy as np

In [2]:
lst = [22,44,66,88]
arr = np.array(lst)
print(arr)

[22 44 66 88]


In [3]:
np.array(lst)

array([22, 44, 66, 88])

In [11]:
np.shape(arr)

(4,)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([22, 44, 66, 88])

In [8]:
lst1=[22,44,66,88]
lst2=[11,33,55,77]
lst3=[1,2,3,4]
arr1 = np.array([lst1,lst2,lst3])

In [9]:
arr1

array([[22, 44, 66, 88],
       [11, 33, 55, 77],
       [ 1,  2,  3,  4]])

In [12]:
np.shape(arr1)

(3, 4)

In [10]:
type(arr1)

numpy.ndarray

In [14]:
arr

array([22, 44, 66, 88])

In [15]:
#indexing
arr[3]

np.int64(88)

In [17]:
arr[3]=55

In [18]:
arr

array([22, 44, 66, 55])

In [19]:
arr[:]

array([22, 44, 66, 55])

In [20]:
arr[2:3]

array([66])

In [21]:
arr[::]

array([22, 44, 66, 55])

In [22]:
arr[-1]

np.int64(55)

In [23]:
arr[-2]

np.int64(66)

In [24]:
arr[::-1]

array([55, 66, 44, 22])

In [25]:
arr[:-1]

array([22, 44, 66])

In [26]:
arr[::-2]

array([55, 44])

In [27]:
arr[::-3]

array([55, 22])

In [28]:
arr

array([22, 44, 66, 55])

In [29]:
arr1

array([[22, 44, 66, 88],
       [11, 33, 55, 77],
       [ 1,  2,  3,  4]])

In [31]:
##    [row , column]  
arr1[:,3]

array([88, 77,  4])

In [33]:
arr1[1,:]

array([11, 33, 55, 77])

In [35]:
arr1[1:,2:]

array([[55, 77],
       [ 3,  4]])

In [39]:
arr1[0:,2:]

array([[66, 88],
       [55, 77],
       [ 3,  4]])

In [40]:
arr1[0:,2:].shape

(3, 2)

In [41]:
## Pick 3 rows and column 0 and column 3
arr1

array([[22, 44, 66, 88],
       [11, 33, 55, 77],
       [ 1,  2,  3,  4]])

In [43]:
arr1[:,::3]

array([[22, 88],
       [11, 77],
       [ 1,  4]])

In [45]:
## EDA
arr

array([22, 44, 66, 55])

In [46]:
arr%2==0

array([ True,  True,  True, False])

In [47]:
arr[arr%2==0]

array([22, 44, 66])

In [48]:
arr*2

array([ 44,  88, 132, 110])

In [52]:
arr**2

array([ 484, 1936, 4356, 3025])

In [50]:
arr

array([22, 44, 66, 55])

In [54]:
arr<50

array([ True,  True, False, False])

In [55]:
arr[arr<50]

array([22, 44])

In [56]:
arr1

array([[22, 44, 66, 88],
       [11, 33, 55, 77],
       [ 1,  2,  3,  4]])

In [57]:
arr1.shape

(3, 4)

In [58]:
## To change shape
arr1.reshape(4,3)

array([[22, 44, 66],
       [88, 11, 33],
       [55, 77,  1],
       [ 2,  3,  4]])

In [126]:
## mechanism to create an array
arr3 = np .arange(1,21,1)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
arr3 = np .arange(1,21,1).reshape(2,10,1)

In [78]:
arr3

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]],

       [[11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]]])

In [80]:
arr3.shape

(20,)

In [85]:
arr3.reshape(1,10,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [87]:
arr3.reshape(2,5,2)     ## the thing is to divide equally, that how many elements

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [88]:
arr1 * arr1

array([[ 484, 1936, 4356, 7744],
       [ 121, 1089, 3025, 5929],
       [   1,    4,    9,   16]])

In [89]:
arr1

array([[22, 44, 66, 88],
       [11, 33, 55, 77],
       [ 1,  2,  3,  4]])

In [90]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
np.ones((2,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [92]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [98]:
np.zeros((3,10,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [101]:
arr1

array([[22, 44, 66, 88],
       [11, 33, 55, 77],
       [ 1,  2,  3,  4]])

In [102]:
## change all the values into zero
np.zeros_like(arr1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [105]:
np.random.randint(10,100)

31

In [113]:
np.random.randint(10,100,2)

array([51, 34], dtype=int32)

In [121]:
## Standard Normal Distribution
np.random.randn(3,5)

array([[ 1.44544003,  1.63583194,  0.93070341,  0.59460244,  0.8950083 ],
       [-0.2263193 , -0.82170235, -0.47170212,  0.21105314,  0.1022416 ],
       [-0.25620903, -0.42291244, -0.67797846, -0.22118904, -0.20936466]])

In [120]:
## Gives Random Value between 0.0 to 1.0
np.random.random_sample((4,6))

array([[0.86364339, 0.80452255, 0.10269398, 0.06602854, 0.13449706,
        0.79736268],
       [0.13612751, 0.51273572, 0.92139594, 0.22316616, 0.18783818,
        0.73774464],
       [0.76708174, 0.32224359, 0.64693355, 0.01682242, 0.90457704,
        0.61145342],
       [0.06266996, 0.27389479, 0.46372479, 0.30342773, 0.77016993,
        0.11661682]])

In [119]:
np.random.random_sample((4,6,1))

array([[[0.59860712],
        [0.35134956],
        [0.16700286],
        [0.10778328],
        [0.98394023],
        [0.48983135]],

       [[0.4954015 ],
        [0.47530559],
        [0.81850564],
        [0.49803948],
        [0.94267163],
        [0.08144388]],

       [[0.92270318],
        [0.64841916],
        [0.38145566],
        [0.47316556],
        [0.26857659],
        [0.71026267]],

       [[0.21795419],
        [0.77639837],
        [0.28332822],
        [0.90831966],
        [0.09695664],
        [0.20960799]]])